# Generated by Django 2.0.4 on 2018-05-10 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0003_remove_matter_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matter',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='authentication.Profile'),
        ),
    ]
