# Generated by Django 2.0.5 on 2018-05-15 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0006_auto_20180515_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matter',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='matter_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
