# Generated by Django 2.0.5 on 2018-05-15 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0011_group_is_private'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IO_template', models.CharField(default='', max_length=15, null=True)),
                ('creator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='protocol_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProtocolOwnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.Group')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocols.Protocol')),
            ],
            options={
                'verbose_name': 'Ownership',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('-----', '-----'), ('Mix', 'Mix'), ('Incubate', 'Incubate'), ('Centrifuge', 'Centrifuge'), ('Decant', 'Decant'), ('Thermocycle', 'Thermocycle'), ('Resuspend', 'Resuspend'), ('Transfer', 'Transfer'), ('Operate', 'Operate')], default='-----', max_length=255)),
                ('protocol', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='protocols.Protocol')),
            ],
        ),
        migrations.AddField(
            model_name='protocol',
            name='groups',
            field=models.ManyToManyField(through='protocols.ProtocolOwnership', to='groups.Group'),
        ),
        migrations.AlterUniqueTogether(
            name='protocolownership',
            unique_together={('protocol', 'group')},
        ),
    ]
