# Generated by Django 2.0.4 on 2018-05-10 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_auto_20180508_1734'),
        ('authentication', '0003_auto_20180413_1910'),
        ('reagents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.Group')),
            ],
            options={
                'verbose_name': 'Ownership',
            },
        ),
        migrations.AddField(
            model_name='matter',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='authentication.Profile'),
        ),
        migrations.AddField(
            model_name='ownership',
            name='matter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reagents.Matter'),
        ),
        migrations.AddField(
            model_name='matter',
            name='groups',
            field=models.ManyToManyField(through='reagents.Ownership', to='groups.Group'),
        ),
        migrations.AlterUniqueTogether(
            name='ownership',
            unique_together={('matter', 'group')},
        ),
    ]
