# Generated by Django 2.0.4 on 2018-05-10 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0002_auto_20180510_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matter',
            name='owner',
        ),
    ]
