# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-13 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='passcode',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
